language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t dschoorl/docker-course-react .

script:
  - docker container run -e CI=true dschoorl/docker-course-react npm run test
